// Stamp the build identity INTO THE SOURCE, so it travels with the code.
//
// WHY, 2026-09-09: /health reported `commit: local-or-unset` on a live service.
// http.ts read RAILWAY_GIT_COMMIT_SHA, and Railway does not inject it for a CLI
// deploy — so the one check built to answer "is MY code running?" could not,
// and "which commit is deployed" stayed an assumption for four weeks.
//   >>> A check that depends on someone else populating a variable is a check
//   >>> with an off switch you do not own.
// The Docker build has no .git, so this must run BEFORE upload, on a machine
// that does. It refuses to overwrite a good stamp with a bad one.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const OUT = new URL('../src/version.ts', import.meta.url);
let sha = null;
try {
  sha = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
  const dirty = execSync('git status --porcelain', { encoding: 'utf8' }).trim().length > 0;
  if (dirty) sha += '+dirty';   // a deploy from an uncommitted tree must say so
} catch {
  sha = null;
}

if (!sha) {
  // No git here (e.g. inside the image). NEVER clobber an existing good stamp.
  const had = existsSync(OUT) && !/unstamped/.test(readFileSync(OUT, 'utf8'));
  console.log(had ? 'stamp: no git, keeping existing stamp' : 'stamp: no git and no stamp -> unstamped');
  if (had) process.exit(0);
  sha = 'unstamped';
}

writeFileSync(OUT,
  '// GENERATED by scripts/stamp_version.mjs - do not edit.\n' +
  `export const BUILD_SHA: string = ${JSON.stringify(sha)};\n` +
  `export const BUILD_TIME: string = ${JSON.stringify(new Date().toISOString())};\n`);
console.log(`stamp: ${sha}`);
